name: GitHub Actions Version Updater

on:
  workflow_dispatch:
  schedule:
    # Automatically run every Sunday at midnight
    - cron:  '0 0 * * 0'

jobs:
  update-actions:
    name: Update GitHub Actions
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          # Use a Personal Access Token (PAT) with 'workflow' scope to authenticate
          token: ${{ secrets.PAT }}

      - name: Update GitHub Actions Versions
        uses: saadmk11/github-actions-version-updater@v0.7.4
        with:
          # This Personal Access Token (PAT) must also have 'workflow' scope
          token: ${{ secrets.PAT }}
          pull_request_title: "ci: Update GitHub Actions to Latest Versions"
